### ISSUE TITLE
README.md cannot be generated using Verb

### ISSUE THREAD

**Issue by ludder** [assemble/assemble-middleware-i18n#51]
I'd like to update the documentation, but I cannot generate the README.md with Verb. I'm getting this error when I run `verb`:

```
helper-base: %j TypeError: Cannot call method 'render' of null
helper-base error: %j TypeError in plugin 'verb-plugin:render'
Message:
    Cannot call method 'render' of null
```

I tried updating the verb dependency to verb 0.6.2 and renaming `verbrc.md` to `verb.md`, but still no luck.

**Comment by jonschlinkert** [comment]
Thanks for doing reporting it. Would you mind trying this:

```markdown
# {%= name %} {%= badge("fury") %}

> {%= description %}

{%= include("install", {save: '--save'}) %}

## Run tests
{%= include("tests") %}

## Contributing
{%= include("contributing") %}

## Author
{%= include("author") %}

## License
{%= copyright() %}
{%= license() %}

***

{%= include("footer") %}
```

Just replace the entire contents with that for now. You can rename to `.verb.md` if you want too, it should be okay either way, but we're gradually getting rid of all of the `rc`s

**Comment by jonschlinkert** [comment]
thanks!

**Comment by ludder** [comment]
Yes, that works! I'll create a PR.

**Comment by jonschlinkert** [comment]
:+1:
